# Generated by Django 5.1.6 on 2025-02-25 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Код скидки')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Значение скидки')),
                ('is_percentage', models.BooleanField(default=True, verbose_name='Является ли скидка процентной')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание скидки')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название налога')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Ставка налога (например, 0.20 для 20%)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание налога')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Общая стоимость заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('discounts', models.ManyToManyField(blank=True, related_name='orders', to='order.discount', verbose_name='Применяемые скидки')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'unique_together': {('order', 'item')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders', through='order.OrderItem', to='item.item', verbose_name='Товары в заказе'),
        ),
        migrations.AddField(
            model_name='order',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='orders', to='order.tax', verbose_name='Применяемые налоги'),
        ),
    ]
